# Generated by Django 2.1.3 on 2018-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_days', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numvar',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
