# Generated by Django 2.1.3 on 2018-11-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_days', '0002_auto_20181103_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offday',
            name='day',
            field=models.DateField(verbose_name='day off'),
        ),
    ]
