# Generated by Django 2.1.3 on 2018-11-04 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_days', '0004_workday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offday',
            name='day',
        ),
        migrations.RemoveField(
            model_name='offday',
            name='desc',
        ),
        migrations.AddField(
            model_name='offday',
            name='from_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offday',
            name='to_day',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
