# Generated by Django 2.1.3 on 2018-11-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_days', '0005_auto_20181104_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offday',
            name='from_day',
            field=models.DateField(verbose_name='from day'),
        ),
        migrations.AlterField(
            model_name='offday',
            name='to_day',
            field=models.DateField(verbose_name='to day'),
        ),
    ]
